// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SalesAPI.Entities {
    
    
    public class CreditCardConfiguration : IEntityTypeConfiguration<CreditCard> {
        
        private string _schema = "Sales";
        
        public virtual void Configure(EntityTypeBuilder<CreditCard> builder) {
            Configure(builder, _schema);
        }
        
        private void Configure(EntityTypeBuilder<CreditCard> builder, string schema) {
            builder.ToTable("CreditCard", schema);
            builder.HasKey(x => x.CreditCardID);

            builder.Property(x => x.CreditCardID).HasColumnName(@"CreditCardID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.CardType).HasColumnName(@"CardType").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            builder.Property(x => x.CardNumber).HasColumnName(@"CardNumber").HasColumnType("nvarchar").IsRequired().HasMaxLength(25);
            builder.Property(x => x.ExpMonth).HasColumnName(@"ExpMonth").HasColumnType("tinyint").IsRequired();
            builder.Property(x => x.ExpYear).HasColumnName(@"ExpYear").HasColumnType("smallint").IsRequired();
            builder.Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            //Foreign keys
        }
    }
}

