// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesAPI.Entities {
    
    
    public partial class Customer {
        
        [Key()]
        [Display(Name = "Customer ID")]
        public int CustomerID { get; set; }
        
        [Display(Name = "Person ID")]
        public System.Int32? PersonID { get; set; }
        
        [Display(Name = "Store ID")]
        public System.Int32? StoreID { get; set; }
        
        [Display(Name = "Territory ID")]
        public System.Int32? TerritoryID { get; set; }
        
        [Display(Name = "Account number")]
        public string AccountNumber { get;private set; }
        
        [Display(Name = "Rowguid")]
        public System.Guid Rowguid { get; set; }
        
        [Display(Name = "Modified date")]
        public System.DateTime ModifiedDate { get; set; }
        
        /// Child SalesOrderHeaders where [SalesOrderHeader].[CustomerID] point to this entity (FK_SalesOrderHeader_Customer_CustomerID)
        public virtual ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; } = new HashSet<SalesOrderHeader>();
        
        // Parent Store pointed by [Customer].([StoreID]) (FK_Customer_Store_StoreID)
        public virtual Store Store { get; set; }
        
        // Parent SalesTerritory pointed by [Customer].([TerritoryID]) (FK_Customer_SalesTerritory_TerritoryID)
        public virtual SalesTerritory SalesTerritory { get; set; }
    }
}

