// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SalesAPI.Entities {
    
    
    public class CustomerConfiguration : IEntityTypeConfiguration<Customer> {
        
        private string _schema = "Sales";
        
        public virtual void Configure(EntityTypeBuilder<Customer> builder) {
            Configure(builder, _schema);
        }
        
        private void Configure(EntityTypeBuilder<Customer> builder, string schema) {
            builder.ToTable("Customer", schema);
            builder.HasKey(x => x.CustomerID);

            builder.Property(x => x.CustomerID).HasColumnName(@"CustomerID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.PersonID).HasColumnName(@"PersonID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.StoreID).HasColumnName(@"StoreID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.TerritoryID).HasColumnName(@"TerritoryID").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.AccountNumber).HasColumnName(@"AccountNumber").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(10).ValueGeneratedOnAddOrUpdate();
            builder.Property(x => x.Rowguid).HasColumnName(@"rowguid").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedOnAddOrUpdate();
            builder.Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            //Foreign keys
            builder.HasOne(a => a.Store).WithMany(b => b.Customers).HasForeignKey(c => c.StoreID).OnDelete(DeleteBehavior.Restrict); // FK_Customer_Store_StoreID
            builder.HasOne(a => a.SalesTerritory).WithMany(b => b.Customers).HasForeignKey(c => c.TerritoryID).OnDelete(DeleteBehavior.Restrict); // FK_Customer_SalesTerritory_TerritoryID
        }
    }
}

