// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using System;

namespace SalesAPI.Entities {
    
    
    public interface IDbEntities : IDbEntityBase {
        
        DbSet<CountryRegionCurrency> CountryRegionCurrencies {
            get;
            set;
        }
        
        DbSet<CreditCard> CreditCards {
            get;
            set;
        }
        
        DbSet<Currency> Currencies {
            get;
            set;
        }
        
        DbSet<CurrencyRate> CurrencyRates {
            get;
            set;
        }
        
        DbSet<Customer> Customers {
            get;
            set;
        }
        
        DbSet<PersonCreditCard> PersonCreditCards {
            get;
            set;
        }
        
        DbSet<SalesOrderDetail> SalesOrderDetails {
            get;
            set;
        }
        
        DbSet<SalesOrderHeader> SalesOrderHeaders {
            get;
            set;
        }
        
        DbSet<SalesOrderHeaderSalesReason> SalesOrderHeaderSalesReasons {
            get;
            set;
        }
        
        DbSet<SalesPerson> SalesPersons {
            get;
            set;
        }
        
        DbSet<SalesPersonQuotaHistory> SalesPersonQuotaHistories {
            get;
            set;
        }
        
        DbSet<SalesReason> SalesReasons {
            get;
            set;
        }
        
        DbSet<SalesTaxRate> SalesTaxRates {
            get;
            set;
        }
        
        DbSet<SalesTerritory> SalesTerritories {
            get;
            set;
        }
        
        DbSet<SalesTerritoryHistory> SalesTerritoryHistories {
            get;
            set;
        }
        
        DbSet<ShoppingCartItem> ShoppingCartItems {
            get;
            set;
        }
        
        DbSet<SpecialOffer> SpecialOffers {
            get;
            set;
        }
        
        DbSet<SpecialOfferProduct> SpecialOfferProducts {
            get;
            set;
        }
        
        DbSet<Store> Stores {
            get;
            set;
        }
    }
}

