// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SalesAPI.Entities {
    
    
    public class PersonCreditCardConfiguration : IEntityTypeConfiguration<PersonCreditCard> {
        
        private string _schema = "Sales";
        
        public virtual void Configure(EntityTypeBuilder<PersonCreditCard> builder) {
            Configure(builder, _schema);
        }
        
        private void Configure(EntityTypeBuilder<PersonCreditCard> builder, string schema) {
            builder.ToTable("PersonCreditCard", schema);
            builder.HasKey(x => new { x.BusinessEntityID, x.CreditCardID });

            builder.Property(x => x.BusinessEntityID).HasColumnName(@"BusinessEntityID").HasColumnType("int").IsRequired();
            builder.Property(x => x.CreditCardID).HasColumnName(@"CreditCardID").HasColumnType("int").IsRequired();
            builder.Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            //Foreign keys
            builder.HasOne(a => a.CreditCard).WithMany(b => b.PersonCreditCards).HasForeignKey(c => c.CreditCardID).OnDelete(DeleteBehavior.Restrict); // FK_PersonCreditCard_CreditCard_CreditCardID
        }
    }
}

