// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesAPI.Entities {
    
    
    public partial class SalesOrderHeader {
        
        [Key()]
        [Display(Name = "Sales order ID")]
        public int SalesOrderID { get; set; }
        
        [Display(Name = "Revision number")]
        public byte RevisionNumber { get; set; }
        
        [Display(Name = "Order date")]
        public System.DateTime OrderDate { get; set; }
        
        [Display(Name = "Due date")]
        public System.DateTime DueDate { get; set; }
        
        [Display(Name = "Ship date")]
        public System.DateTime? ShipDate { get; set; }
        
        [Display(Name = "Status")]
        public byte Status { get; set; }
        
        [Display(Name = "Online order flag")]
        public bool OnlineOrderFlag { get; set; }
        
        [Display(Name = "Sales order number")]
        public string SalesOrderNumber { get;private set; }
        
        [Display(Name = "Purchase order number")]
        public string PurchaseOrderNumber { get; set; }
        
        [Display(Name = "Account number")]
        public string AccountNumber { get; set; }
        
        [Display(Name = "Customer ID")]
        public int CustomerID { get; set; }
        
        [Display(Name = "Sales person ID")]
        public System.Int32? SalesPersonID { get; set; }
        
        [Display(Name = "Territory ID")]
        public System.Int32? TerritoryID { get; set; }
        
        [Display(Name = "Bill to address ID")]
        public int BillToAddressID { get; set; }
        
        [Display(Name = "Ship to address ID")]
        public int ShipToAddressID { get; set; }
        
        [Display(Name = "Ship method ID")]
        public int ShipMethodID { get; set; }
        
        [Display(Name = "Credit card ID")]
        public System.Int32? CreditCardID { get; set; }
        
        [Display(Name = "Credit card approval code")]
        public string CreditCardApprovalCode { get; set; }
        
        [Display(Name = "Currency rate ID")]
        public System.Int32? CurrencyRateID { get; set; }
        
        [Display(Name = "Sub total")]
        public decimal SubTotal { get; set; }
        
        [Display(Name = "Tax amt")]
        public decimal TaxAmt { get; set; }
        
        [Display(Name = "Freight")]
        public decimal Freight { get; set; }
        
        [Display(Name = "Total due")]
        public decimal TotalDue { get;private set; }
        
        [Display(Name = "Comment")]
        public string Comment { get; set; }
        
        [Display(Name = "Rowguid")]
        public System.Guid Rowguid { get; set; }
        
        [Display(Name = "Modified date")]
        public System.DateTime ModifiedDate { get; set; }
        
        /// Child SalesOrderDetails where [SalesOrderDetail].[SalesOrderID] point to this entity (FK_SalesOrderDetail_SalesOrderHeader_SalesOrderID)
        public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; } = new HashSet<SalesOrderDetail>();
        
        /// Child SalesOrderHeaderSalesReasons where [SalesOrderHeaderSalesReason].[SalesOrderID] point to this entity (FK_SalesOrderHeaderSalesReason_SalesOrderHeader_SalesOrderID)
        public virtual ICollection<SalesOrderHeaderSalesReason> SalesOrderHeaderSalesReasons { get; set; } = new HashSet<SalesOrderHeaderSalesReason>();
        
        // Parent Customer pointed by [SalesOrderHeader].([CustomerID]) (FK_SalesOrderHeader_Customer_CustomerID)
        public virtual Customer Customer { get; set; }
        
        // Parent SalesPerson pointed by [SalesOrderHeader].([SalesPersonID]) (FK_SalesOrderHeader_SalesPerson_SalesPersonID)
        public virtual SalesPerson SalesPerson { get; set; }
        
        // Parent SalesTerritory pointed by [SalesOrderHeader].([TerritoryID]) (FK_SalesOrderHeader_SalesTerritory_TerritoryID)
        public virtual SalesTerritory SalesTerritory { get; set; }
        
        // Parent CreditCard pointed by [SalesOrderHeader].([CreditCardID]) (FK_SalesOrderHeader_CreditCard_CreditCardID)
        public virtual CreditCard CreditCard { get; set; }
        
        // Parent CurrencyRate pointed by [SalesOrderHeader].([CurrencyRateID]) (FK_SalesOrderHeader_CurrencyRate_CurrencyRateID)
        public virtual CurrencyRate CurrencyRate { get; set; }
    }
}

