// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SalesAPI.Entities {
    
    
    public class SalesTaxRateConfiguration : IEntityTypeConfiguration<SalesTaxRate> {
        
        private string _schema = "Sales";
        
        public virtual void Configure(EntityTypeBuilder<SalesTaxRate> builder) {
            Configure(builder, _schema);
        }
        
        private void Configure(EntityTypeBuilder<SalesTaxRate> builder, string schema) {
            builder.ToTable("SalesTaxRate", schema);
            builder.HasKey(x => x.SalesTaxRateID);

            builder.Property(x => x.SalesTaxRateID).HasColumnName(@"SalesTaxRateID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.StateProvinceID).HasColumnName(@"StateProvinceID").HasColumnType("int").IsRequired();
            builder.Property(x => x.TaxType).HasColumnName(@"TaxType").HasColumnType("tinyint").IsRequired();
            builder.Property(x => x.TaxRate).HasColumnName(@"TaxRate").HasColumnType("smallmoney").IsRequired().HasColumnType("decimal10,4)");
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            builder.Property(x => x.Rowguid).HasColumnName(@"rowguid").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedOnAddOrUpdate();
            builder.Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            //Foreign keys
        }
    }
}

