// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SalesAPI.Entities {
    
    
    public class SalesPersonQuotaHistoryConfiguration : IEntityTypeConfiguration<SalesPersonQuotaHistory> {
        
        private string _schema = "Sales";
        
        public virtual void Configure(EntityTypeBuilder<SalesPersonQuotaHistory> builder) {
            Configure(builder, _schema);
        }
        
        private void Configure(EntityTypeBuilder<SalesPersonQuotaHistory> builder, string schema) {
            builder.ToTable("SalesPersonQuotaHistory", schema);
            builder.HasKey(x => new { x.BusinessEntityID, x.QuotaDate });

            builder.Property(x => x.BusinessEntityID).HasColumnName(@"BusinessEntityID").HasColumnType("int").IsRequired();
            builder.Property(x => x.QuotaDate).HasColumnName(@"QuotaDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.SalesQuota).HasColumnName(@"SalesQuota").HasColumnType("money").IsRequired().HasColumnType("decimal19,4)");
            builder.Property(x => x.Rowguid).HasColumnName(@"rowguid").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedOnAddOrUpdate();
            builder.Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            //Foreign keys
            builder.HasOne(a => a.SalesPerson).WithMany(b => b.SalesPersonQuotaHistories).HasForeignKey(c => c.BusinessEntityID).OnDelete(DeleteBehavior.Restrict); // FK_SalesPersonQuotaHistory_SalesPerson_BusinessEntityID
        }
    }
}

