// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SalesAPI.Entities {
    
    
    public class SalesTerritoryConfiguration : IEntityTypeConfiguration<SalesTerritory> {
        
        private string _schema = "Sales";
        
        public virtual void Configure(EntityTypeBuilder<SalesTerritory> builder) {
            Configure(builder, _schema);
        }
        
        private void Configure(EntityTypeBuilder<SalesTerritory> builder, string schema) {
            builder.ToTable("SalesTerritory", schema);
            builder.HasKey(x => x.TerritoryID);

            builder.Property(x => x.TerritoryID).HasColumnName(@"TerritoryID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            builder.Property(x => x.CountryRegionCode).HasColumnName(@"CountryRegionCode").HasColumnType("nvarchar").IsRequired().HasMaxLength(3);
            builder.Property(x => x.Group).HasColumnName(@"Group").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            builder.Property(x => x.SalesYTD).HasColumnName(@"SalesYTD").HasColumnType("money").IsRequired().HasColumnType("decimal19,4)");
            builder.Property(x => x.SalesLastYear).HasColumnName(@"SalesLastYear").HasColumnType("money").IsRequired().HasColumnType("decimal19,4)");
            builder.Property(x => x.CostYTD).HasColumnName(@"CostYTD").HasColumnType("money").IsRequired().HasColumnType("decimal19,4)");
            builder.Property(x => x.CostLastYear).HasColumnName(@"CostLastYear").HasColumnType("money").IsRequired().HasColumnType("decimal19,4)");
            builder.Property(x => x.Rowguid).HasColumnName(@"rowguid").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedOnAddOrUpdate();
            builder.Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            //Foreign keys
        }
    }
}

