// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesAPI.Entities {
    
    
    public partial class SalesPerson {
        
        [Key()]
        [Display(Name = "Business entity ID")]
        public int BusinessEntityID { get; set; }
        
        [Display(Name = "Territory ID")]
        public System.Int32? TerritoryID { get; set; }
        
        [Display(Name = "Sales quota")]
        public System.Decimal? SalesQuota { get; set; }
        
        [Display(Name = "Bonus")]
        public decimal Bonus { get; set; }
        
        [Display(Name = "Commission pct")]
        public decimal CommissionPct { get; set; }
        
        [Display(Name = "Sales ytd")]
        public decimal SalesYTD { get; set; }
        
        [Display(Name = "Sales last year")]
        public decimal SalesLastYear { get; set; }
        
        [Display(Name = "Rowguid")]
        public System.Guid Rowguid { get; set; }
        
        [Display(Name = "Modified date")]
        public System.DateTime ModifiedDate { get; set; }
        
        /// Child SalesOrderHeaders where [SalesOrderHeader].[SalesPersonID] point to this entity (FK_SalesOrderHeader_SalesPerson_SalesPersonID)
        public virtual ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; } = new HashSet<SalesOrderHeader>();
        
        /// Child SalesPersonQuotaHistories where [SalesPersonQuotaHistory].[BusinessEntityID] point to this entity (FK_SalesPersonQuotaHistory_SalesPerson_BusinessEntityID)
        public virtual ICollection<SalesPersonQuotaHistory> SalesPersonQuotaHistories { get; set; } = new HashSet<SalesPersonQuotaHistory>();
        
        /// Child SalesTerritoryHistories where [SalesTerritoryHistory].[BusinessEntityID] point to this entity (FK_SalesTerritoryHistory_SalesPerson_BusinessEntityID)
        public virtual ICollection<SalesTerritoryHistory> SalesTerritoryHistories { get; set; } = new HashSet<SalesTerritoryHistory>();
        
        /// Child Stores where [Store].[SalesPersonID] point to this entity (FK_Store_SalesPerson_SalesPersonID)
        public virtual ICollection<Store> Stores { get; set; } = new HashSet<Store>();
        
        // Parent SalesTerritory pointed by [SalesPerson].([TerritoryID]) (FK_SalesPerson_SalesTerritory_TerritoryID)
        public virtual SalesTerritory SalesTerritory { get; set; }
    }
}

