// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesAPI.Entities {
    
    
    public partial class SalesOrderDetail {
        
        [Key()]
        [Column(Order=1)]
        [Display(Name = "Sales order ID")]
        public int SalesOrderID { get; set; }
        
        [Key()]
        [Column(Order=2)]
        [Display(Name = "Sales order detail ID")]
        public int SalesOrderDetailID { get; set; }
        
        [Display(Name = "Carrier tracking number")]
        public string CarrierTrackingNumber { get; set; }
        
        [Display(Name = "Order qty")]
        public short OrderQty { get; set; }
        
        [Display(Name = "Product ID")]
        public int ProductID { get; set; }
        
        [Display(Name = "Special offer ID")]
        public int SpecialOfferID { get; set; }
        
        [Display(Name = "Unit price")]
        public decimal UnitPrice { get; set; }
        
        [Display(Name = "Unit price discount")]
        public decimal UnitPriceDiscount { get; set; }
        
        [Display(Name = "Line total")]
        public decimal LineTotal { get;private set; }
        
        [Display(Name = "Rowguid")]
        public System.Guid Rowguid { get; set; }
        
        [Display(Name = "Modified date")]
        public System.DateTime ModifiedDate { get; set; }
        
        // Parent SalesOrderHeader pointed by [SalesOrderDetail].([SalesOrderID]) (FK_SalesOrderDetail_SalesOrderHeader_SalesOrderID)
        public virtual SalesOrderHeader SalesOrderHeader { get; set; }
        
        // Parent SpecialOfferProduct pointed by [SalesOrderDetail].([SpecialOfferID], [ProductID]) (FK_SalesOrderDetail_SpecialOfferProduct_SpecialOfferIDProductID)
        public virtual SpecialOfferProduct SpecialOfferProduct { get; set; }
    }
}

