// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SalesAPI.Entities {
    
    
    public class SalesOrderHeaderSalesReasonConfiguration : IEntityTypeConfiguration<SalesOrderHeaderSalesReason> {
        
        private string _schema = "Sales";
        
        public virtual void Configure(EntityTypeBuilder<SalesOrderHeaderSalesReason> builder) {
            Configure(builder, _schema);
        }
        
        private void Configure(EntityTypeBuilder<SalesOrderHeaderSalesReason> builder, string schema) {
            builder.ToTable("SalesOrderHeaderSalesReason", schema);
            builder.HasKey(x => new { x.SalesOrderID, x.SalesReasonID });

            builder.Property(x => x.SalesOrderID).HasColumnName(@"SalesOrderID").HasColumnType("int").IsRequired();
            builder.Property(x => x.SalesReasonID).HasColumnName(@"SalesReasonID").HasColumnType("int").IsRequired();
            builder.Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            //Foreign keys
            builder.HasOne(a => a.SalesOrderHeader).WithMany(b => b.SalesOrderHeaderSalesReasons).HasForeignKey(c => c.SalesOrderID); // FK_SalesOrderHeaderSalesReason_SalesOrderHeader_SalesOrderID
            builder.HasOne(a => a.SalesReason).WithMany(b => b.SalesOrderHeaderSalesReasons).HasForeignKey(c => c.SalesReasonID).OnDelete(DeleteBehavior.Restrict); // FK_SalesOrderHeaderSalesReason_SalesReason_SalesReasonID
        }
    }
}

