// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesAPI.Entities {
    
    
    public partial class SalesTaxRate {
        
        [Key()]
        [Display(Name = "Sales tax rate ID")]
        public int SalesTaxRateID { get; set; }
        
        [Display(Name = "State province ID")]
        public int StateProvinceID { get; set; }
        
        [Display(Name = "Tax type")]
        public byte TaxType { get; set; }
        
        [Display(Name = "Tax rate")]
        public decimal TaxRate { get; set; }
        
        [Display(Name = "Name")]
        public string Name { get; set; }
        
        [Display(Name = "Rowguid")]
        public System.Guid Rowguid { get; set; }
        
        [Display(Name = "Modified date")]
        public System.DateTime ModifiedDate { get; set; }
    }
}

