// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SalesAPI.Entities {
    
    
    public class ShoppingCartItemConfiguration : IEntityTypeConfiguration<ShoppingCartItem> {
        
        private string _schema = "Sales";
        
        public virtual void Configure(EntityTypeBuilder<ShoppingCartItem> builder) {
            Configure(builder, _schema);
        }
        
        private void Configure(EntityTypeBuilder<ShoppingCartItem> builder, string schema) {
            builder.ToTable("ShoppingCartItem", schema);
            builder.HasKey(x => x.ShoppingCartItemID);

            builder.Property(x => x.ShoppingCartItemID).HasColumnName(@"ShoppingCartItemID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.ShoppingCartID).HasColumnName(@"ShoppingCartID").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            builder.Property(x => x.Quantity).HasColumnName(@"Quantity").HasColumnType("int").IsRequired();
            builder.Property(x => x.ProductID).HasColumnName(@"ProductID").HasColumnType("int").IsRequired();
            builder.Property(x => x.DateCreated).HasColumnName(@"DateCreated").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            //Foreign keys
        }
    }
}

