// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesAPI.Entities {
    
    
    public partial class ShoppingCartItem {
        
        [Key()]
        [Display(Name = "Shopping cart item ID")]
        public int ShoppingCartItemID { get; set; }
        
        [Display(Name = "Shopping cart ID")]
        public string ShoppingCartID { get; set; }
        
        [Display(Name = "Quantity")]
        public int Quantity { get; set; }
        
        [Display(Name = "Product ID")]
        public int ProductID { get; set; }
        
        [Display(Name = "Date created")]
        public System.DateTime DateCreated { get; set; }
        
        [Display(Name = "Modified date")]
        public System.DateTime ModifiedDate { get; set; }
    }
}

