// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesAPI.Entities {
    
    
    public partial class SpecialOffer {
        
        [Key()]
        [Display(Name = "Special offer ID")]
        public int SpecialOfferID { get; set; }
        
        [Display(Name = "Description")]
        public string Description { get; set; }
        
        [Display(Name = "Discount pct")]
        public decimal DiscountPct { get; set; }
        
        [Display(Name = "Type")]
        public string Type { get; set; }
        
        [Display(Name = "Category")]
        public string Category { get; set; }
        
        [Display(Name = "Start date")]
        public System.DateTime StartDate { get; set; }
        
        [Display(Name = "End date")]
        public System.DateTime EndDate { get; set; }
        
        [Display(Name = "Min qty")]
        public int MinQty { get; set; }
        
        [Display(Name = "Max qty")]
        public System.Int32? MaxQty { get; set; }
        
        [Display(Name = "Rowguid")]
        public System.Guid Rowguid { get; set; }
        
        [Display(Name = "Modified date")]
        public System.DateTime ModifiedDate { get; set; }
        
        /// Child SpecialOfferProducts where [SpecialOfferProduct].[SpecialOfferID] point to this entity (FK_SpecialOfferProduct_SpecialOffer_SpecialOfferID)
        public virtual ICollection<SpecialOfferProduct> SpecialOfferProducts { get; set; } = new HashSet<SpecialOfferProduct>();
    }
}

