// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesAPI.Entities {
    
    
    public partial class SpecialOfferProduct {
        
        [Key()]
        [Column(Order=1)]
        [Display(Name = "Special offer ID")]
        public int SpecialOfferID { get; set; }
        
        [Key()]
        [Column(Order=2)]
        [Display(Name = "Product ID")]
        public int ProductID { get; set; }
        
        [Display(Name = "Rowguid")]
        public System.Guid Rowguid { get; set; }
        
        [Display(Name = "Modified date")]
        public System.DateTime ModifiedDate { get; set; }
        
        /// Child SalesOrderDetails where [SalesOrderDetail].([ProductID], [SpecialOfferID]) point to this entity (FK_SalesOrderDetail_SpecialOfferProduct_SpecialOfferIDProductID)
        public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; } = new HashSet<SalesOrderDetail>();
        
        // Parent SpecialOffer pointed by [SpecialOfferProduct].([SpecialOfferID]) (FK_SpecialOfferProduct_SpecialOffer_SpecialOfferID)
        public virtual SpecialOffer SpecialOffer { get; set; }
    }
}

