// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SalesAPI.Entities {
    
    
    public class SpecialOfferConfiguration : IEntityTypeConfiguration<SpecialOffer> {
        
        private string _schema = "Sales";
        
        public virtual void Configure(EntityTypeBuilder<SpecialOffer> builder) {
            Configure(builder, _schema);
        }
        
        private void Configure(EntityTypeBuilder<SpecialOffer> builder, string schema) {
            builder.ToTable("SpecialOffer", schema);
            builder.HasKey(x => x.SpecialOfferID);

            builder.Property(x => x.SpecialOfferID).HasColumnName(@"SpecialOfferID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            builder.Property(x => x.DiscountPct).HasColumnName(@"DiscountPct").HasColumnType("smallmoney").IsRequired().HasColumnType("decimal10,4)");
            builder.Property(x => x.Type).HasColumnName(@"Type").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            builder.Property(x => x.Category).HasColumnName(@"Category").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            builder.Property(x => x.StartDate).HasColumnName(@"StartDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.EndDate).HasColumnName(@"EndDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.MinQty).HasColumnName(@"MinQty").HasColumnType("int").IsRequired();
            builder.Property(x => x.MaxQty).HasColumnName(@"MaxQty").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Rowguid).HasColumnName(@"rowguid").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedOnAddOrUpdate();
            builder.Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            //Foreign keys
        }
    }
}

