// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SalesAPI.Entities {
    
    
    public class SpecialOfferProductConfiguration : IEntityTypeConfiguration<SpecialOfferProduct> {
        
        private string _schema = "Sales";
        
        public virtual void Configure(EntityTypeBuilder<SpecialOfferProduct> builder) {
            Configure(builder, _schema);
        }
        
        private void Configure(EntityTypeBuilder<SpecialOfferProduct> builder, string schema) {
            builder.ToTable("SpecialOfferProduct", schema);
            builder.HasKey(x => new { x.SpecialOfferID, x.ProductID });

            builder.Property(x => x.SpecialOfferID).HasColumnName(@"SpecialOfferID").HasColumnType("int").IsRequired();
            builder.Property(x => x.ProductID).HasColumnName(@"ProductID").HasColumnType("int").IsRequired();
            builder.Property(x => x.Rowguid).HasColumnName(@"rowguid").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedOnAddOrUpdate();
            builder.Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            //Foreign keys
            builder.HasOne(a => a.SpecialOffer).WithMany(b => b.SpecialOfferProducts).HasForeignKey(c => c.SpecialOfferID).OnDelete(DeleteBehavior.Restrict); // FK_SpecialOfferProduct_SpecialOffer_SpecialOfferID
        }
    }
}

