// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesAPI.Entities {
    
    
    public partial class Store {
        
        [Key()]
        [Display(Name = "Business entity ID")]
        public int BusinessEntityID { get; set; }
        
        [Display(Name = "Name")]
        public string Name { get; set; }
        
        [Display(Name = "Sales person ID")]
        public System.Int32? SalesPersonID { get; set; }
        
        [Display(Name = "Demographics")]
        public string Demographics { get; set; }
        
        [Display(Name = "Rowguid")]
        public System.Guid Rowguid { get; set; }
        
        [Display(Name = "Modified date")]
        public System.DateTime ModifiedDate { get; set; }
        
        /// Child Customers where [Customer].[StoreID] point to this entity (FK_Customer_Store_StoreID)
        public virtual ICollection<Customer> Customers { get; set; } = new HashSet<Customer>();
        
        // Parent SalesPerson pointed by [Store].([SalesPersonID]) (FK_Store_SalesPerson_SalesPersonID)
        public virtual SalesPerson SalesPerson { get; set; }
    }
}

