// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using AutoMapper;
using InstantHelper;
using LinqKit;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SalesAPI.Entities;
using SalesAPI.Models;
using SalesAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Threading.Tasks;

namespace SalesAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("CountryRegionCurrency")]
    public class CountryRegionCurrencyController : ControllerBase {
        
        private IDbEntities _entities;
        
        private IMapper _mapper;
        
        private ILoggerManager _logger;
        
        public CountryRegionCurrencyController(EntitiesContext context, IMapper mapper, ILoggerManager logger) {
            _entities = context;
            _mapper = mapper;
            _logger = logger;
        }
        
        [HttpGet("")]
        public IQueryable<CountryRegionCurrencyModel> GetAllCountryRegionCurrencies() {

            ICollection<CountryRegionCurrencyModel> models = _mapper.Map<ICollection<CountryRegionCurrencyModel>>(_entities.CountryRegionCurrencies);

            return models.AsQueryable();
        }
        
        [HttpGet("Paged")]
        public IPagedList<CountryRegionCurrencyModel> GetPagedCountryRegionCurrencies(int pageIndex, int pageSize) {

            ICollection<CountryRegionCurrencyModel> models = _mapper.Map<ICollection<CountryRegionCurrencyModel>>(_entities.CountryRegionCurrencies);

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{countryRegionCode}/{currencyCode}")]
        public async Task<ActionResult> GetCountryRegionCurrency_ByCountryRegionCodeCurrencyCode(string countryRegionCode, string currencyCode) {

            CountryRegionCurrencyModel model;

          var query = await SearchByPk(countryRegionCode, currencyCode);
            if (!query.Any()) {
              return NotFound();
            }
            else {
           model = _mapper.Map<CountryRegionCurrencyModel>(query.SingleOrDefault());
            }

            return Ok(model);
        }
        
        [HttpGet("GetCountryRegionCurrency_ByCurrencyCode/{currencyCode}")]
        public IQueryable<CountryRegionCurrencyModel> GetCountryRegionCurrency_ByCurrencyCode(string currencyCode) {

            ICollection<CountryRegionCurrencyModel> models = _mapper.Map<ICollection<CountryRegionCurrencyModel>>(_entities.CountryRegionCurrencies.Where(x => x.CurrencyCode == currencyCode));

            return models.AsQueryable();
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddCountryRegionCurrency([FromBody]CountryRegionCurrencyModel model) {

            CountryRegionCurrency entity = null;

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var matchCurrencyCode = _entities.Currencies.Where(x => x.CurrencyCode.Equals(model.CurrencyCode));
            if (!matchCurrencyCode.Any()) {
              return BadRequest("Foreign Key Violation;" + string.Format("CurrencyCode = '{0}' doesn't exist in the system.", model.CurrencyCode));
            }


            var search = SearchbyUnique(model.CountryRegionCode, model.CurrencyCode);
            if (search.Result.Count() > 0) {
              return BadRequest("Duplicate Record;" + string.Format("Record already exists in the system with this(these) value(s):{0}, {1}", model.CountryRegionCode, model.CurrencyCode));
            }

           try
           {
                 entity = _mapper.Map<CountryRegionCurrency>(model);
                _entities.CountryRegionCurrencies.Add(entity);
               await _entities.SaveChangesAsync();
            }
            catch (Exception e)
            {
                throw e;
            }

            _logger.LogInfo(string.Format("CountryRegionCurrency added with values: '{0}'", JsonConvert.SerializeObject(model)));

            return CreatedAtAction("GetCountryRegionCurrency_ByCountryRegionCodeCurrencyCode", new {countryRegionCode = entity.CountryRegionCode, currencyCode = entity.CurrencyCode}, model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateCountryRegionCurrency([FromBody]CountryRegionCurrencyModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var query = SearchByPk(model.CountryRegionCode, model.CurrencyCode).Result;
            if (!query.Any()) {
              return BadRequest("Record Not Found;" + string.Format("CountryRegionCurrency with _countryRegionCode, _currencyCode = '{0}', '{1}' doesn't exist.",model.CountryRegionCode, model.CurrencyCode));
            }
            var matchCurrencyCode = _entities.Currencies.Where(x => x.CurrencyCode.Equals(model.CurrencyCode));
            if (!matchCurrencyCode.Any()) {
              return BadRequest("Foreign Key Violation;" + string.Format("CurrencyCode = '{0}' doesn't exist in the system.", model.CurrencyCode));
            }


           try
           {
            CountryRegionCurrency entity = query.SingleOrDefault();
             entity = model.ToEntity(entity);
               await _entities.SaveChangesAsync();
            }
            catch (Exception e)
            {
                throw e;
            }
            _logger.LogInfo(string.Format("CountryRegionCurrency updated with values: '{0}'", JsonConvert.SerializeObject(model)));

            return StatusCode((int)HttpStatusCode.NoContent);
        }
        
        [HttpDelete("{countryRegionCode}/{currencyCode}")]
        public async Task<ActionResult> DeleteCountryRegionCurrency(string countryRegionCode, string currencyCode) {

            var query = SearchByPk(countryRegionCode, currencyCode).Result;
            if (!query.Any()) {
              return BadRequest("Record Not Found;" + string.Format("CountryRegionCurrency with _countryRegionCode, _currencyCode = '{0}', '{1}' doesn't exist.",countryRegionCode, currencyCode));
            }
            var entity = query.SingleOrDefault();

           try
           {
                _entities.CountryRegionCurrencies.Remove(entity);
               await _entities.SaveChangesAsync();
            }
            catch (Exception e)
            {
                throw e;
            }
            _logger.LogInfo(string.Format("CountryRegionCurrency deleted with values: '{0}'", JsonConvert.SerializeObject(new CountryRegionCurrencyModel(entity))));

            return Ok(new CountryRegionCurrencyModel(entity));
        }
        
        private async Task<IQueryable<CountryRegionCurrency>> SearchByPk(string countryRegionCode, string currencyCode) {

            var pb = PredicateBuilder.New<CountryRegionCurrency>();
            pb = pb.And(p => p.CountryRegionCode.Equals(countryRegionCode));
            pb = pb.And(p => p.CurrencyCode.Equals(currencyCode));

            return await Task.FromResult(_entities.CountryRegionCurrencies.AsExpandable().Where(pb));
        }
        
        private async Task<IQueryable<CountryRegionCurrency>> SearchbyUnique(string countryRegionCode, string currencyCode) {

            var pb = PredicateBuilder.New<CountryRegionCurrency>();
            pb = pb.And(p => p.CountryRegionCode.Equals(countryRegionCode));
            pb = pb.And(p => p.CurrencyCode.Equals(currencyCode));

            return await Task.FromResult(_entities.CountryRegionCurrencies.AsExpandable().Where(pb));
        }
    }
}

