// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using AutoMapper;
using InstantHelper;
using LinqKit;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SalesAPI.Entities;
using SalesAPI.Models;
using SalesAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Threading.Tasks;

namespace SalesAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("CreditCard")]
    public class CreditCardController : ControllerBase {
        
        private IDbEntities _entities;
        
        private IMapper _mapper;
        
        private ILoggerManager _logger;
        
        public CreditCardController(EntitiesContext context, IMapper mapper, ILoggerManager logger) {
            _entities = context;
            _mapper = mapper;
            _logger = logger;
        }
        
        [HttpGet("")]
        public IQueryable<CreditCardModel> GetAllCreditCards() {

            ICollection<CreditCardModel> models = _mapper.Map<ICollection<CreditCardModel>>(_entities.CreditCards);

            return models.AsQueryable();
        }
        
        [HttpGet("Paged")]
        public IPagedList<CreditCardModel> GetPagedCreditCards(int pageIndex, int pageSize) {

            ICollection<CreditCardModel> models = _mapper.Map<ICollection<CreditCardModel>>(_entities.CreditCards);

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{creditCardID}")]
        public async Task<ActionResult> GetCreditCard_ByCreditCardID(int creditCardID) {

            CreditCardModel model;

          var query = await SearchByPk(creditCardID);
            if (!query.Any()) {
              return NotFound();
            }
            else {
           model = _mapper.Map<CreditCardModel>(query.SingleOrDefault());
            }

            return Ok(model);
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddCreditCard([FromBody]CreditCardModel model) {

            CreditCard entity = null;

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }


            var search = SearchbyUnique(model.CardNumber);
            if (search.Result.Count() > 0) {
              return BadRequest("Duplicate Record;" + string.Format("Record already exists in the system with this(these) value(s):{0}", model.CardNumber));
            }

           try
           {
                 entity = _mapper.Map<CreditCard>(model);
                _entities.CreditCards.Add(entity);
               await _entities.SaveChangesAsync();
            }
            catch (Exception e)
            {
                throw e;
            }

            model.CreditCardID = entity.CreditCardID;
            _logger.LogInfo(string.Format("CreditCard added with values: '{0}'", JsonConvert.SerializeObject(model)));

            return CreatedAtAction("GetCreditCard_ByCreditCardID", new {creditCardID = entity.CreditCardID}, model);
        }
        
        [HttpPut("{creditCardID}")]
        public async Task<ActionResult> UpdateCreditCard(int creditCardID, [FromBody]CreditCardModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var query = SearchByPk(creditCardID).Result;
            if (!query.Any()) {
              ModelState.AddModelError("Record Not Found", string.Format("CreditCard with _creditCardID = '{0}' doesn't exist.",creditCardID)); 
              return BadRequest(ModelState);
            }

           try
           {
            CreditCard entity = query.SingleOrDefault();
             entity = model.ToEntity(entity);
               await _entities.SaveChangesAsync();
            }
            catch (Exception e)
            {
                throw e;
            }
            _logger.LogInfo(string.Format("CreditCard updated with values: '{0}'", JsonConvert.SerializeObject(model)));

            return StatusCode((int)HttpStatusCode.NoContent);
        }
        
        [HttpDelete("{creditCardID}")]
        public async Task<ActionResult> DeleteCreditCard(int creditCardID) {

            var query = SearchByPk(creditCardID).Result;
            if (!query.Any()) {
              return BadRequest("Record Not Found;" + string.Format("CreditCard with _creditCardID = '{0}' doesn't exist.",creditCardID));
            }
            var entity = query.SingleOrDefault();

           try
           {
                _entities.CreditCards.Remove(entity);
               await _entities.SaveChangesAsync();
            }
            catch (Exception e)
            {
                throw e;
            }
            _logger.LogInfo(string.Format("CreditCard deleted with values: '{0}'", JsonConvert.SerializeObject(new CreditCardModel(entity))));

            return Ok(new CreditCardModel(entity));
        }
        
        private async Task<IQueryable<CreditCard>> SearchByPk(int creditCardID) {

            var pb = PredicateBuilder.New<CreditCard>();
            pb = pb.And(p => p.CreditCardID.Equals(creditCardID));

            return await Task.FromResult(_entities.CreditCards.AsExpandable().Where(pb));
        }
        
        private async Task<IQueryable<CreditCard>> SearchbyUnique(string cardNumber) {

            var pb = PredicateBuilder.New<CreditCard>();
            pb = pb.And(p => p.CardNumber.Equals(cardNumber));

            return await Task.FromResult(_entities.CreditCards.AsExpandable().Where(pb));
        }
    }
}

