// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using AutoMapper;
using InstantHelper;
using LinqKit;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SalesAPI.Entities;
using SalesAPI.Models;
using SalesAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Threading.Tasks;

namespace SalesAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("SalesPerson")]
    public class SalesPersonController : ControllerBase {
        
        private IDbEntities _entities;
        
        private IMapper _mapper;
        
        private ILoggerManager _logger;
        
        public SalesPersonController(EntitiesContext context, IMapper mapper, ILoggerManager logger) {
            _entities = context;
            _mapper = mapper;
            _logger = logger;
        }
        
        [HttpGet("")]
        public IQueryable<SalesPersonModel> GetAllSalesPersons() {

            ICollection<SalesPersonModel> models = _mapper.Map<ICollection<SalesPersonModel>>(_entities.SalesPersons);

            return models.AsQueryable();
        }
        
        [HttpGet("Paged")]
        public IPagedList<SalesPersonModel> GetPagedSalesPersons(int pageIndex, int pageSize) {

            ICollection<SalesPersonModel> models = _mapper.Map<ICollection<SalesPersonModel>>(_entities.SalesPersons);

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{businessEntityID}")]
        public async Task<ActionResult> GetSalesPerson_ByBusinessEntityID(int businessEntityID) {

            SalesPersonModel model;

          var query = await SearchByPk(businessEntityID);
            if (!query.Any()) {
              return NotFound();
            }
            else {
           model = _mapper.Map<SalesPersonModel>(query.SingleOrDefault());
            }

            return Ok(model);
        }
        
        [HttpGet("GetSalesPerson_ByTerritoryID/{territoryID}")]
        public IQueryable<SalesPersonModel> GetSalesPerson_ByTerritoryID(int territoryID) {

            ICollection<SalesPersonModel> models = _mapper.Map<ICollection<SalesPersonModel>>(_entities.SalesPersons.Where(x => x.TerritoryID == territoryID));

            return models.AsQueryable();
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddSalesPerson([FromBody]SalesPersonModel model) {

            SalesPerson entity = null;

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            if (model.TerritoryID != null) {
                var matchTerritoryID = _entities.SalesTerritories.Where(x => x.TerritoryID.Equals(model.TerritoryID));
                if (!matchTerritoryID.Any()) {
              return BadRequest("Foreign Key Violation;" + string.Format("TerritoryID = '{0}' doesn't exist in the system.", model.TerritoryID));
                }
            }


            var search = SearchbyUnique(model.BusinessEntityID);
            if (search.Result.Count() > 0) {
              return BadRequest("Duplicate Record;" + string.Format("Record already exists in the system with this(these) value(s):{0}", model.BusinessEntityID));
            }

           try
           {
                System.Int32 maxCount = 0;
                if(_entities.SalesPersons.Count() > 0)
                    maxCount = _entities.SalesPersons.Max(x => x.BusinessEntityID);
                model.BusinessEntityID= ++maxCount;
                 entity = _mapper.Map<SalesPerson>(model);
                _entities.SalesPersons.Add(entity);
               await _entities.SaveChangesAsync();
            }
            catch (Exception e)
            {
                throw e;
            }

            _logger.LogInfo(string.Format("SalesPerson added with values: '{0}'", JsonConvert.SerializeObject(model)));

            return CreatedAtAction("GetSalesPerson_ByBusinessEntityID", new {businessEntityID = entity.BusinessEntityID}, model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateSalesPerson([FromBody]SalesPersonModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var query = SearchByPk(model.BusinessEntityID).Result;
            if (!query.Any()) {
              return BadRequest("Record Not Found;" + string.Format("SalesPerson with _businessEntityID = '{0}' doesn't exist.",model.BusinessEntityID));
            }
            if (model.TerritoryID != null) {
                var matchTerritoryID = _entities.SalesTerritories.Where(x => x.TerritoryID.Equals(model.TerritoryID));
                if (!matchTerritoryID.Any()) {
              return BadRequest("Foreign Key Violation;" + string.Format("TerritoryID = '{0}' doesn't exist in the system.", model.TerritoryID));
                }
            }


           try
           {
            SalesPerson entity = query.SingleOrDefault();
             entity = model.ToEntity(entity);
               await _entities.SaveChangesAsync();
            }
            catch (Exception e)
            {
                throw e;
            }
            _logger.LogInfo(string.Format("SalesPerson updated with values: '{0}'", JsonConvert.SerializeObject(model)));

            return StatusCode((int)HttpStatusCode.NoContent);
        }
        
        [HttpDelete("{businessEntityID}")]
        public async Task<ActionResult> DeleteSalesPerson(int businessEntityID) {

            var query = SearchByPk(businessEntityID).Result;
            if (!query.Any()) {
              return BadRequest("Record Not Found;" + string.Format("SalesPerson with _businessEntityID = '{0}' doesn't exist.",businessEntityID));
            }
            var entity = query.SingleOrDefault();

           try
           {
                _entities.SalesPersons.Remove(entity);
               await _entities.SaveChangesAsync();
            }
            catch (Exception e)
            {
                throw e;
            }
            _logger.LogInfo(string.Format("SalesPerson deleted with values: '{0}'", JsonConvert.SerializeObject(new SalesPersonModel(entity))));

            return Ok(new SalesPersonModel(entity));
        }
        
        private async Task<IQueryable<SalesPerson>> SearchByPk(int businessEntityID) {

            var pb = PredicateBuilder.New<SalesPerson>();
            pb = pb.And(p => p.BusinessEntityID.Equals(businessEntityID));

            return await Task.FromResult(_entities.SalesPersons.AsExpandable().Where(pb));
        }
        
        private async Task<IQueryable<SalesPerson>> SearchbyUnique(int businessEntityID) {

            var pb = PredicateBuilder.New<SalesPerson>();
            pb = pb.And(p => p.BusinessEntityID.Equals(businessEntityID));

            return await Task.FromResult(_entities.SalesPersons.AsExpandable().Where(pb));
        }
    }
}

