// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using AutoMapper;
using InstantHelper;
using LinqKit;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SalesAPI.Entities;
using SalesAPI.Models;
using SalesAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Threading.Tasks;

namespace SalesAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("SalesReason")]
    public class SalesReasonController : ControllerBase {
        
        private IDbEntities _entities;
        
        private IMapper _mapper;
        
        private ILoggerManager _logger;
        
        public SalesReasonController(EntitiesContext context, IMapper mapper, ILoggerManager logger) {
            _entities = context;
            _mapper = mapper;
            _logger = logger;
        }
        
        [HttpGet("")]
        public IQueryable<SalesReasonModel> GetAllSalesReasons() {

            ICollection<SalesReasonModel> models = _mapper.Map<ICollection<SalesReasonModel>>(_entities.SalesReasons);

            return models.AsQueryable();
        }
        
        [HttpGet("Paged")]
        public IPagedList<SalesReasonModel> GetPagedSalesReasons(int pageIndex, int pageSize) {

            ICollection<SalesReasonModel> models = _mapper.Map<ICollection<SalesReasonModel>>(_entities.SalesReasons);

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{salesReasonID}")]
        public async Task<ActionResult> GetSalesReason_BySalesReasonID(int salesReasonID) {

            SalesReasonModel model;

          var query = await SearchByPk(salesReasonID);
            if (!query.Any()) {
              return NotFound();
            }
            else {
           model = _mapper.Map<SalesReasonModel>(query.SingleOrDefault());
            }

            return Ok(model);
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddSalesReason([FromBody]SalesReasonModel model) {

            SalesReason entity = null;

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }


            var search = SearchbyUnique(model.Name, model.ReasonType);
            if (search.Result.Count() > 0) {
              return BadRequest("Duplicate Record;" + string.Format("Record already exists in the system with this(these) value(s):{0}, {1}", model.Name, model.ReasonType));
            }

           try
           {
                 entity = _mapper.Map<SalesReason>(model);
                _entities.SalesReasons.Add(entity);
               await _entities.SaveChangesAsync();
            }
            catch (Exception e)
            {
                throw e;
            }

            model.SalesReasonID = entity.SalesReasonID;
            _logger.LogInfo(string.Format("SalesReason added with values: '{0}'", JsonConvert.SerializeObject(model)));

            return CreatedAtAction("GetSalesReason_BySalesReasonID", new {salesReasonID = entity.SalesReasonID}, model);
        }
        
        [HttpPut("{salesReasonID}")]
        public async Task<ActionResult> UpdateSalesReason(int salesReasonID, [FromBody]SalesReasonModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var query = SearchByPk(salesReasonID).Result;
            if (!query.Any()) {
              ModelState.AddModelError("Record Not Found", string.Format("SalesReason with _salesReasonID = '{0}' doesn't exist.",salesReasonID)); 
              return BadRequest(ModelState);
            }

           try
           {
            SalesReason entity = query.SingleOrDefault();
             entity = model.ToEntity(entity);
               await _entities.SaveChangesAsync();
            }
            catch (Exception e)
            {
                throw e;
            }
            _logger.LogInfo(string.Format("SalesReason updated with values: '{0}'", JsonConvert.SerializeObject(model)));

            return StatusCode((int)HttpStatusCode.NoContent);
        }
        
        [HttpDelete("{salesReasonID}")]
        public async Task<ActionResult> DeleteSalesReason(int salesReasonID) {

            var query = SearchByPk(salesReasonID).Result;
            if (!query.Any()) {
              return BadRequest("Record Not Found;" + string.Format("SalesReason with _salesReasonID = '{0}' doesn't exist.",salesReasonID));
            }
            var entity = query.SingleOrDefault();

           try
           {
                _entities.SalesReasons.Remove(entity);
               await _entities.SaveChangesAsync();
            }
            catch (Exception e)
            {
                throw e;
            }
            _logger.LogInfo(string.Format("SalesReason deleted with values: '{0}'", JsonConvert.SerializeObject(new SalesReasonModel(entity))));

            return Ok(new SalesReasonModel(entity));
        }
        
        private async Task<IQueryable<SalesReason>> SearchByPk(int salesReasonID) {

            var pb = PredicateBuilder.New<SalesReason>();
            pb = pb.And(p => p.SalesReasonID.Equals(salesReasonID));

            return await Task.FromResult(_entities.SalesReasons.AsExpandable().Where(pb));
        }
        
        private async Task<IQueryable<SalesReason>> SearchbyUnique(string name, string reasonType) {

            var pb = PredicateBuilder.New<SalesReason>();
            pb = pb.And(p => p.Name.Equals(name));
            pb = pb.And(p => p.ReasonType.Equals(reasonType));

            return await Task.FromResult(_entities.SalesReasons.AsExpandable().Where(pb));
        }
    }
}

