// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using AutoMapper;
using InstantHelper;
using LinqKit;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SalesAPI.Entities;
using SalesAPI.Models;
using SalesAPI.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Threading.Tasks;

namespace SalesAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("SalesTerritory")]
    public class SalesTerritoryController : ControllerBase {
        
        private IDbEntities _entities;
        
        private IMapper _mapper;
        
        private ILoggerManager _logger;
        
        public SalesTerritoryController(EntitiesContext context, IMapper mapper, ILoggerManager logger) {
            _entities = context;
            _mapper = mapper;
            _logger = logger;
        }
        
        [HttpGet("")]
        public IQueryable<SalesTerritoryModel> GetAllSalesTerritories() {

            ICollection<SalesTerritoryModel> models = _mapper.Map<ICollection<SalesTerritoryModel>>(_entities.SalesTerritories);

            return models.AsQueryable();
        }
        
        [HttpGet("Paged")]
        public IPagedList<SalesTerritoryModel> GetPagedSalesTerritories(int pageIndex, int pageSize) {

            ICollection<SalesTerritoryModel> models = _mapper.Map<ICollection<SalesTerritoryModel>>(_entities.SalesTerritories);

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{territoryID}")]
        public async Task<ActionResult> GetSalesTerritory_ByTerritoryID(int territoryID) {

            SalesTerritoryModel model;

          var query = await SearchByPk(territoryID);
            if (!query.Any()) {
              return NotFound();
            }
            else {
           model = _mapper.Map<SalesTerritoryModel>(query.SingleOrDefault());
            }

            return Ok(model);
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddSalesTerritory([FromBody]SalesTerritoryModel model) {

            SalesTerritory entity = null;

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }


            var search = SearchbyUnique(model.Name);
            if (search.Result.Count() > 0) {
              return BadRequest("Duplicate Record;" + string.Format("Record already exists in the system with this(these) value(s):{0}", model.Name));
            }

           try
           {
                 entity = _mapper.Map<SalesTerritory>(model);
                _entities.SalesTerritories.Add(entity);
               await _entities.SaveChangesAsync();
            }
            catch (Exception e)
            {
                throw e;
            }

            model.TerritoryID = entity.TerritoryID;
            _logger.LogInfo(string.Format("SalesTerritory added with values: '{0}'", JsonConvert.SerializeObject(model)));

            return CreatedAtAction("GetSalesTerritory_ByTerritoryID", new {territoryID = entity.TerritoryID}, model);
        }
        
        [HttpPut("{territoryID}")]
        public async Task<ActionResult> UpdateSalesTerritory(int territoryID, [FromBody]SalesTerritoryModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var query = SearchByPk(territoryID).Result;
            if (!query.Any()) {
              ModelState.AddModelError("Record Not Found", string.Format("SalesTerritory with _territoryID = '{0}' doesn't exist.",territoryID)); 
              return BadRequest(ModelState);
            }

           try
           {
            SalesTerritory entity = query.SingleOrDefault();
             entity = model.ToEntity(entity);
               await _entities.SaveChangesAsync();
            }
            catch (Exception e)
            {
                throw e;
            }
            _logger.LogInfo(string.Format("SalesTerritory updated with values: '{0}'", JsonConvert.SerializeObject(model)));

            return StatusCode((int)HttpStatusCode.NoContent);
        }
        
        [HttpDelete("{territoryID}")]
        public async Task<ActionResult> DeleteSalesTerritory(int territoryID) {

            var query = SearchByPk(territoryID).Result;
            if (!query.Any()) {
              return BadRequest("Record Not Found;" + string.Format("SalesTerritory with _territoryID = '{0}' doesn't exist.",territoryID));
            }
            var entity = query.SingleOrDefault();

           try
           {
                _entities.SalesTerritories.Remove(entity);
               await _entities.SaveChangesAsync();
            }
            catch (Exception e)
            {
                throw e;
            }
            _logger.LogInfo(string.Format("SalesTerritory deleted with values: '{0}'", JsonConvert.SerializeObject(new SalesTerritoryModel(entity))));

            return Ok(new SalesTerritoryModel(entity));
        }
        
        private async Task<IQueryable<SalesTerritory>> SearchByPk(int territoryID) {

            var pb = PredicateBuilder.New<SalesTerritory>();
            pb = pb.And(p => p.TerritoryID.Equals(territoryID));

            return await Task.FromResult(_entities.SalesTerritories.AsExpandable().Where(pb));
        }
        
        private async Task<IQueryable<SalesTerritory>> SearchbyUnique(string name) {

            var pb = PredicateBuilder.New<SalesTerritory>();
            pb = pb.And(p => p.Name.Equals(name));

            return await Task.FromResult(_entities.SalesTerritories.AsExpandable().Where(pb));
        }
    }
}

