// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using AutoMapper;
using SalesAPI.Entities;

namespace SalesAPI.Models {
    
    
    public class AutoMapperProfiles : Profile {
        
        public AutoMapperProfiles() {
            CreateMap<CountryRegionCurrency, CountryRegionCurrencyModel>();
            CreateMap<CountryRegionCurrencyModel, CountryRegionCurrency>();
            CreateMap<CreditCard, CreditCardModel>();
            CreateMap<CreditCardModel, CreditCard>();
            CreateMap<Currency, CurrencyModel>();
            CreateMap<CurrencyModel, Currency>();
            CreateMap<CurrencyRate, CurrencyRateModel>();
            CreateMap<CurrencyRateModel, CurrencyRate>();
            CreateMap<Customer, CustomerModel>();
            CreateMap<CustomerModel, Customer>();
            CreateMap<PersonCreditCard, PersonCreditCardModel>();
            CreateMap<PersonCreditCardModel, PersonCreditCard>();
            CreateMap<SalesOrderDetail, SalesOrderDetailModel>();
            CreateMap<SalesOrderDetailModel, SalesOrderDetail>();
            CreateMap<SalesOrderHeader, SalesOrderHeaderModel>();
            CreateMap<SalesOrderHeaderModel, SalesOrderHeader>();
            CreateMap<SalesOrderHeaderSalesReason, SalesOrderHeaderSalesReasonModel>();
            CreateMap<SalesOrderHeaderSalesReasonModel, SalesOrderHeaderSalesReason>();
            CreateMap<SalesPerson, SalesPersonModel>();
            CreateMap<SalesPersonModel, SalesPerson>();
            CreateMap<SalesPersonQuotaHistory, SalesPersonQuotaHistoryModel>();
            CreateMap<SalesPersonQuotaHistoryModel, SalesPersonQuotaHistory>();
            CreateMap<SalesReason, SalesReasonModel>();
            CreateMap<SalesReasonModel, SalesReason>();
            CreateMap<SalesTaxRate, SalesTaxRateModel>();
            CreateMap<SalesTaxRateModel, SalesTaxRate>();
            CreateMap<SalesTerritory, SalesTerritoryModel>();
            CreateMap<SalesTerritoryModel, SalesTerritory>();
            CreateMap<SalesTerritoryHistory, SalesTerritoryHistoryModel>();
            CreateMap<SalesTerritoryHistoryModel, SalesTerritoryHistory>();
            CreateMap<ShoppingCartItem, ShoppingCartItemModel>();
            CreateMap<ShoppingCartItemModel, ShoppingCartItem>();
            CreateMap<SpecialOffer, SpecialOfferModel>();
            CreateMap<SpecialOfferModel, SpecialOffer>();
            CreateMap<SpecialOfferProduct, SpecialOfferProductModel>();
            CreateMap<SpecialOfferProductModel, SpecialOfferProduct>();
            CreateMap<Store, StoreModel>();
            CreateMap<StoreModel, Store>();
        }
    }
}

