// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using SalesAPI.Entities;
using SalesAPI.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SalesAPI.Models {
    
    
    public class CountryRegionCurrencyModel {
        
        protected internal string _countryRegionCode;
        
        protected internal string _currencyCode;
        
        protected internal System.DateTime _modifiedDate;
        
        public CountryRegionCurrencyModel() {
        }
        
        internal CountryRegionCurrencyModel(CountryRegionCurrency entity) {
            this._countryRegionCode = entity.CountryRegionCode;
            this._currencyCode = entity.CurrencyCode;
            this._modifiedDate = entity.ModifiedDate;
        }
        
        [Required()]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Country region code")]
        public string CountryRegionCode {
            get {
                return this._countryRegionCode;
            }
            set {
                this._countryRegionCode = value;
            }
        }
        
        [Required()]
        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Currency code")]
        public string CurrencyCode {
            get {
                return this._currencyCode;
            }
            set {
                this._currencyCode = value;
            }
        }
        
        [Required()]
        [DataType(DataType.DateTime)]
        [Display(Name = "Modified date")]
        public System.DateTime ModifiedDate {
            get {
                return this._modifiedDate;
            }
            set {
                this._modifiedDate = value;
            }
        }
        
        public override int GetHashCode() {
            int hash = 0;
            hash ^=CountryRegionCode.GetHashCode();
            hash ^=CurrencyCode.GetHashCode();
            return hash;
        }
        
        public override string ToString() {
            return CountryRegionCode
                 + "-" + CurrencyCode
;
        }
        
        public override bool Equals(object obj) {
        bool result = false;

            if (obj is CountryRegionCurrencyModel) {
                CountryRegionCurrencyModel toCompare = (CountryRegionCurrencyModel)obj;
              if(toCompare != null)
              {
                  result = Equals(toCompare);
              }
            }

            return result;
        }
        
        public virtual bool Equals(CountryRegionCurrencyModel toCompare) {

        bool result = false;

            if (toCompare != null) {
                result = string.Compare(toCompare.CountryRegionCode, CountryRegionCode, true) == 0
             && string.Compare(toCompare.CurrencyCode, CurrencyCode, true) == 0
;
            }

            return result;
        }
    }
}

