// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using SalesAPI.Entities;
using SalesAPI.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SalesAPI.Models {
    
    
    public class SalesOrderHeaderSalesReasonModel {
        
        protected internal int _salesOrderID;
        
        protected internal int _salesReasonID;
        
        protected internal System.DateTime _modifiedDate;
        
        public SalesOrderHeaderSalesReasonModel() {
        }
        
        internal SalesOrderHeaderSalesReasonModel(SalesOrderHeaderSalesReason entity) {
            this._salesOrderID = entity.SalesOrderID;
            this._salesReasonID = entity.SalesReasonID;
            this._modifiedDate = entity.ModifiedDate;
        }
        
        [Required()]
        [Display(Name = "Sales order ID")]
        public int SalesOrderID {
            get {
                return this._salesOrderID;
            }
            set {
                this._salesOrderID = value;
            }
        }
        
        [Required()]
        [Display(Name = "Sales reason ID")]
        public int SalesReasonID {
            get {
                return this._salesReasonID;
            }
            set {
                this._salesReasonID = value;
            }
        }
        
        [Required()]
        [DataType(DataType.DateTime)]
        [Display(Name = "Modified date")]
        public System.DateTime ModifiedDate {
            get {
                return this._modifiedDate;
            }
            set {
                this._modifiedDate = value;
            }
        }
        
        public override int GetHashCode() {
            int hash = 0;
            hash ^=SalesOrderID.GetHashCode();
            hash ^=SalesReasonID.GetHashCode();
            return hash;
        }
        
        public override string ToString() {
            return SalesOrderID.ToString()
                 + "-" + SalesReasonID.ToString()
;
        }
        
        public override bool Equals(object obj) {
        bool result = false;

            if (obj is SalesOrderHeaderSalesReasonModel) {
                SalesOrderHeaderSalesReasonModel toCompare = (SalesOrderHeaderSalesReasonModel)obj;
              if(toCompare != null)
              {
                  result = Equals(toCompare);
              }
            }

            return result;
        }
        
        public virtual bool Equals(SalesOrderHeaderSalesReasonModel toCompare) {

        bool result = false;

            if (toCompare != null) {
                result = toCompare.SalesOrderID == SalesOrderID
             && toCompare.SalesReasonID == SalesReasonID
;
            }

            return result;
        }
    }
}

