// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using SalesAPI.Entities;
using SalesAPI.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SalesAPI.Models {
    
    
    public class SalesOrderDetailModel {
        
        protected internal int _salesOrderID;
        
        protected internal int _salesOrderDetailID;
        
        protected internal string _carrierTrackingNumber;
        
        protected internal short _orderQty;
        
        protected internal int _productID;
        
        protected internal int _specialOfferID;
        
        protected internal decimal _unitPrice;
        
        protected internal decimal _unitPriceDiscount;
        
        protected internal decimal _lineTotal;
        
        protected internal System.Guid _rowguid;
        
        protected internal System.DateTime _modifiedDate;
        
        public SalesOrderDetailModel() {
        }
        
        internal SalesOrderDetailModel(SalesOrderDetail entity) {
            this._salesOrderID = entity.SalesOrderID;
            this._salesOrderDetailID = entity.SalesOrderDetailID;
            this._carrierTrackingNumber = entity.CarrierTrackingNumber;
            this._orderQty = entity.OrderQty;
            this._productID = entity.ProductID;
            this._specialOfferID = entity.SpecialOfferID;
            this._unitPrice = entity.UnitPrice;
            this._unitPriceDiscount = entity.UnitPriceDiscount;
            _lineTotal = entity.LineTotal;
            _rowguid = entity.Rowguid;
            this._modifiedDate = entity.ModifiedDate;
        }
        
        [Required()]
        [Display(Name = "Sales order ID")]
        public int SalesOrderID {
            get {
                return this._salesOrderID;
            }
            set {
                this._salesOrderID = value;
            }
        }
        
        [Display(Name = "Sales order detail ID")]
        public int SalesOrderDetailID {
            get {
                return this._salesOrderDetailID;
            }
            set {
                this._salesOrderDetailID = value;
            }
        }
        
        [MaxLength(25)]
        [StringLength(25)]
        [Display(Name = "Carrier tracking number")]
        public string CarrierTrackingNumber {
            get {
                return this._carrierTrackingNumber;
            }
            set {
                this._carrierTrackingNumber = value;
            }
        }
        
        [Required()]
        [Display(Name = "Order qty")]
        public short OrderQty {
            get {
                return this._orderQty;
            }
            set {
                this._orderQty = value;
            }
        }
        
        [Required()]
        [Display(Name = "Product ID")]
        public int ProductID {
            get {
                return this._productID;
            }
            set {
                this._productID = value;
            }
        }
        
        [Required()]
        [Display(Name = "Special offer ID")]
        public int SpecialOfferID {
            get {
                return this._specialOfferID;
            }
            set {
                this._specialOfferID = value;
            }
        }
        
        [Required()]
        [DataType(DataType.Currency)]
        [Display(Name = "Unit price")]
        public decimal UnitPrice {
            get {
                return this._unitPrice;
            }
            set {
                this._unitPrice = value;
            }
        }
        
        [Required()]
        [DataType(DataType.Currency)]
        [Display(Name = "Unit price discount")]
        public decimal UnitPriceDiscount {
            get {
                return this._unitPriceDiscount;
            }
            set {
                this._unitPriceDiscount = value;
            }
        }
        
        [Display(Name = "Line total")]
        public decimal LineTotal {
            get {
                return this._lineTotal;
            }
        }
        
        [Display(Name = "Rowguid")]
        public System.Guid Rowguid {
            get {
                return this._rowguid;
            }
        }
        
        [Required()]
        [DataType(DataType.DateTime)]
        [Display(Name = "Modified date")]
        public System.DateTime ModifiedDate {
            get {
                return this._modifiedDate;
            }
            set {
                this._modifiedDate = value;
            }
        }
        
        public override int GetHashCode() {
            int hash = 0;
            hash ^=Rowguid.GetHashCode();
            return hash;
        }
        
        public override string ToString() {
            return SalesOrderID.ToString()
                 + "-" + OrderQty.ToString()
                 + "-" + ProductID.ToString()
                 + "-" + SpecialOfferID.ToString()
                 + "-" + UnitPrice.ToString()
                 + "-" + UnitPriceDiscount.ToString()
;
        }
        
        public override bool Equals(object obj) {
        bool result = false;

            if (obj is SalesOrderDetailModel) {
                SalesOrderDetailModel toCompare = (SalesOrderDetailModel)obj;
              if(toCompare != null)
              {
                  result = Equals(toCompare);
              }
            }

            return result;
        }
        
        public virtual bool Equals(SalesOrderDetailModel toCompare) {

        bool result = false;

            if (toCompare != null) {
                result = toCompare.SalesOrderID == SalesOrderID
             && toCompare.CarrierTrackingNumber.Equals(CarrierTrackingNumber)
             && toCompare.OrderQty == OrderQty
             && toCompare.ProductID == ProductID
             && toCompare.SpecialOfferID == SpecialOfferID
             && toCompare.UnitPrice == UnitPrice
             && toCompare.UnitPriceDiscount == UnitPriceDiscount
;
            }

            return result;
        }
    }
}

