// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using SalesAPI.Entities;
using SalesAPI.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SalesAPI.Models {
    
    
    public class SalesOrderHeaderModel {
        
        protected internal int _salesOrderID;
        
        protected internal byte _revisionNumber;
        
        protected internal System.DateTime _orderDate;
        
        protected internal System.DateTime _dueDate;
        
        protected internal System.DateTime? _shipDate;
        
        protected internal byte _status;
        
        protected internal bool _onlineOrderFlag;
        
        protected internal string _salesOrderNumber;
        
        protected internal string _purchaseOrderNumber;
        
        protected internal string _accountNumber;
        
        protected internal int _customerID;
        
        protected internal int? _salesPersonID;
        
        protected internal int? _territoryID;
        
        protected internal int _billToAddressID;
        
        protected internal int _shipToAddressID;
        
        protected internal int _shipMethodID;
        
        protected internal int? _creditCardID;
        
        protected internal string _creditCardApprovalCode;
        
        protected internal int? _currencyRateID;
        
        protected internal decimal _subTotal;
        
        protected internal decimal _taxAmt;
        
        protected internal decimal _freight;
        
        protected internal decimal _totalDue;
        
        protected internal string _comment;
        
        protected internal System.Guid _rowguid;
        
        protected internal System.DateTime _modifiedDate;
        
        public SalesOrderHeaderModel() {
        }
        
        internal SalesOrderHeaderModel(SalesOrderHeader entity) {
            this._salesOrderID = entity.SalesOrderID;
            this._revisionNumber = entity.RevisionNumber;
            this._orderDate = entity.OrderDate;
            this._dueDate = entity.DueDate;
            this._shipDate = entity.ShipDate;
            this._status = entity.Status;
            this._onlineOrderFlag = entity.OnlineOrderFlag;
            _salesOrderNumber = entity.SalesOrderNumber;
            this._purchaseOrderNumber = entity.PurchaseOrderNumber;
            this._accountNumber = entity.AccountNumber;
            this._customerID = entity.CustomerID;
            this._salesPersonID = entity.SalesPersonID;
            this._territoryID = entity.TerritoryID;
            this._billToAddressID = entity.BillToAddressID;
            this._shipToAddressID = entity.ShipToAddressID;
            this._shipMethodID = entity.ShipMethodID;
            this._creditCardID = entity.CreditCardID;
            this._creditCardApprovalCode = entity.CreditCardApprovalCode;
            this._currencyRateID = entity.CurrencyRateID;
            this._subTotal = entity.SubTotal;
            this._taxAmt = entity.TaxAmt;
            this._freight = entity.Freight;
            _totalDue = entity.TotalDue;
            this._comment = entity.Comment;
            _rowguid = entity.Rowguid;
            this._modifiedDate = entity.ModifiedDate;
        }
        
        [Display(Name = "Sales order ID")]
        public int SalesOrderID {
            get {
                return this._salesOrderID;
            }
            set {
                this._salesOrderID = value;
            }
        }
        
        [Required()]
        [Display(Name = "Revision number")]
        public byte RevisionNumber {
            get {
                return this._revisionNumber;
            }
            set {
                this._revisionNumber = value;
            }
        }
        
        [Required()]
        [DataType(DataType.DateTime)]
        [Display(Name = "Order date")]
        public System.DateTime OrderDate {
            get {
                return this._orderDate;
            }
            set {
                this._orderDate = value;
            }
        }
        
        [Required()]
        [DataType(DataType.DateTime)]
        [Display(Name = "Due date")]
        public System.DateTime DueDate {
            get {
                return this._dueDate;
            }
            set {
                this._dueDate = value;
            }
        }
        
        [DataType(DataType.DateTime)]
        [Display(Name = "Ship date")]
        public System.DateTime? ShipDate {
            get {
                return this._shipDate;
            }
            set {
                this._shipDate = value;
            }
        }
        
        [Required()]
        [Display(Name = "Status")]
        public byte Status {
            get {
                return this._status;
            }
            set {
                this._status = value;
            }
        }
        
        [Required()]
        [Display(Name = "Online order flag")]
        public bool OnlineOrderFlag {
            get {
                return this._onlineOrderFlag;
            }
            set {
                this._onlineOrderFlag = value;
            }
        }
        
        [MaxLength(25)]
        [StringLength(25)]
        [Display(Name = "Sales order number")]
        public string SalesOrderNumber {
            get {
                return this._salesOrderNumber;
            }
        }
        
        [MaxLength(25)]
        [StringLength(25)]
        [Display(Name = "Purchase order number")]
        public string PurchaseOrderNumber {
            get {
                return this._purchaseOrderNumber;
            }
            set {
                this._purchaseOrderNumber = value;
            }
        }
        
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "Account number")]
        public string AccountNumber {
            get {
                return this._accountNumber;
            }
            set {
                this._accountNumber = value;
            }
        }
        
        [Required()]
        [Display(Name = "Customer ID")]
        public int CustomerID {
            get {
                return this._customerID;
            }
            set {
                this._customerID = value;
            }
        }
        
        [Display(Name = "Sales person ID")]
        public int? SalesPersonID {
            get {
                return this._salesPersonID;
            }
            set {
                this._salesPersonID = value;
            }
        }
        
        [Display(Name = "Territory ID")]
        public int? TerritoryID {
            get {
                return this._territoryID;
            }
            set {
                this._territoryID = value;
            }
        }
        
        [Required()]
        [Display(Name = "Bill to address ID")]
        public int BillToAddressID {
            get {
                return this._billToAddressID;
            }
            set {
                this._billToAddressID = value;
            }
        }
        
        [Required()]
        [Display(Name = "Ship to address ID")]
        public int ShipToAddressID {
            get {
                return this._shipToAddressID;
            }
            set {
                this._shipToAddressID = value;
            }
        }
        
        [Required()]
        [Display(Name = "Ship method ID")]
        public int ShipMethodID {
            get {
                return this._shipMethodID;
            }
            set {
                this._shipMethodID = value;
            }
        }
        
        [Display(Name = "Credit card ID")]
        public int? CreditCardID {
            get {
                return this._creditCardID;
            }
            set {
                this._creditCardID = value;
            }
        }
        
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "Credit card approval code")]
        public string CreditCardApprovalCode {
            get {
                return this._creditCardApprovalCode;
            }
            set {
                this._creditCardApprovalCode = value;
            }
        }
        
        [Display(Name = "Currency rate ID")]
        public int? CurrencyRateID {
            get {
                return this._currencyRateID;
            }
            set {
                this._currencyRateID = value;
            }
        }
        
        [Required()]
        [DataType(DataType.Currency)]
        [Display(Name = "Sub total")]
        public decimal SubTotal {
            get {
                return this._subTotal;
            }
            set {
                this._subTotal = value;
            }
        }
        
        [Required()]
        [DataType(DataType.Currency)]
        [Display(Name = "Tax amt")]
        public decimal TaxAmt {
            get {
                return this._taxAmt;
            }
            set {
                this._taxAmt = value;
            }
        }
        
        [Required()]
        [DataType(DataType.Currency)]
        [Display(Name = "Freight")]
        public decimal Freight {
            get {
                return this._freight;
            }
            set {
                this._freight = value;
            }
        }
        
        [DataType(DataType.Currency)]
        [Display(Name = "Total due")]
        public decimal TotalDue {
            get {
                return this._totalDue;
            }
        }
        
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Comment")]
        public string Comment {
            get {
                return this._comment;
            }
            set {
                this._comment = value;
            }
        }
        
        [Display(Name = "Rowguid")]
        public System.Guid Rowguid {
            get {
                return this._rowguid;
            }
        }
        
        [Required()]
        [DataType(DataType.DateTime)]
        [Display(Name = "Modified date")]
        public System.DateTime ModifiedDate {
            get {
                return this._modifiedDate;
            }
            set {
                this._modifiedDate = value;
            }
        }
        
        /// Child SalesOrderDetails where [SalesOrderDetail].[SalesOrderID] point to this entity (FK_SalesOrderDetail_SalesOrderHeader_SalesOrderID)
        public virtual ICollection<SalesOrderDetailModel> SalesOrderDetailsModel { get; set; } = new HashSet<SalesOrderDetailModel>();
        
        /// Child SalesOrderHeaderSalesReasons where [SalesOrderHeaderSalesReason].[SalesOrderID] point to this entity (FK_SalesOrderHeaderSalesReason_SalesOrderHeader_SalesOrderID)
        public virtual ICollection<SalesOrderHeaderSalesReasonModel> SalesOrderHeaderSalesReasonsModel { get; set; } = new HashSet<SalesOrderHeaderSalesReasonModel>();
        
        public override int GetHashCode() {
            int hash = 0;
            hash ^=Rowguid.GetHashCode();
            return hash;
        }
        
        public override string ToString() {
            return RevisionNumber.ToString()
                 + "-" + DueDate.ToShortDateString()
                 + "-" + Status.ToString()
                 + "-" + OnlineOrderFlag.ToString()
                 + "-" + CustomerID.ToString()
                 + "-" + BillToAddressID.ToString()
                 + "-" + ShipToAddressID.ToString()
                 + "-" + ShipMethodID.ToString()
                 + "-" + SubTotal.ToString()
                 + "-" + TaxAmt.ToString()
                 + "-" + Freight.ToString()
;
        }
        
        public override bool Equals(object obj) {
        bool result = false;

            if (obj is SalesOrderHeaderModel) {
                SalesOrderHeaderModel toCompare = (SalesOrderHeaderModel)obj;
              if(toCompare != null)
              {
                  result = Equals(toCompare);
              }
            }

            return result;
        }
        
        public virtual bool Equals(SalesOrderHeaderModel toCompare) {

        bool result = false;

            if (toCompare != null) {
                result = toCompare.RevisionNumber == RevisionNumber
             && toCompare.DueDate.Equals(DueDate)
             && toCompare.ShipDate.Equals(ShipDate)
             && toCompare.Status == Status
             && toCompare.OnlineOrderFlag == OnlineOrderFlag
             && toCompare.PurchaseOrderNumber.Equals(PurchaseOrderNumber)
             && toCompare.AccountNumber.Equals(AccountNumber)
             && toCompare.CustomerID == CustomerID
             && toCompare.SalesPersonID.Equals(SalesPersonID)
             && toCompare.TerritoryID.Equals(TerritoryID)
             && toCompare.BillToAddressID == BillToAddressID
             && toCompare.ShipToAddressID == ShipToAddressID
             && toCompare.ShipMethodID == ShipMethodID
             && toCompare.CreditCardID.Equals(CreditCardID)
             && toCompare.CreditCardApprovalCode.Equals(CreditCardApprovalCode)
             && toCompare.CurrencyRateID.Equals(CurrencyRateID)
             && toCompare.SubTotal == SubTotal
             && toCompare.TaxAmt == TaxAmt
             && toCompare.Freight == Freight
             && toCompare.Comment.Equals(Comment)
;
            }

            return result;
        }
    }
}

