// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using SalesAPI.Entities;
using SalesAPI.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SalesAPI.Models {
    
    
    public class SpecialOfferModel {
        
        protected internal int _specialOfferID;
        
        protected internal string _description;
        
        protected internal decimal _discountPct;
        
        protected internal string _type;
        
        protected internal string _category;
        
        protected internal System.DateTime _startDate;
        
        protected internal System.DateTime _endDate;
        
        protected internal int _minQty;
        
        protected internal int? _maxQty;
        
        protected internal System.Guid _rowguid;
        
        protected internal System.DateTime _modifiedDate;
        
        public SpecialOfferModel() {
        }
        
        internal SpecialOfferModel(SpecialOffer entity) {
            this._specialOfferID = entity.SpecialOfferID;
            this._description = entity.Description;
            this._discountPct = entity.DiscountPct;
            this._type = entity.Type;
            this._category = entity.Category;
            this._startDate = entity.StartDate;
            this._endDate = entity.EndDate;
            this._minQty = entity.MinQty;
            this._maxQty = entity.MaxQty;
            _rowguid = entity.Rowguid;
            this._modifiedDate = entity.ModifiedDate;
        }
        
        [Display(Name = "Special offer ID")]
        public int SpecialOfferID {
            get {
                return this._specialOfferID;
            }
            set {
                this._specialOfferID = value;
            }
        }
        
        [Required()]
        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Description")]
        public string Description {
            get {
                return this._description;
            }
            set {
                this._description = value;
            }
        }
        
        [Required()]
        [DataType(DataType.Currency)]
        [Display(Name = "Discount pct")]
        public decimal DiscountPct {
            get {
                return this._discountPct;
            }
            set {
                this._discountPct = value;
            }
        }
        
        [Required()]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Type")]
        public string Type {
            get {
                return this._type;
            }
            set {
                this._type = value;
            }
        }
        
        [Required()]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Category")]
        public string Category {
            get {
                return this._category;
            }
            set {
                this._category = value;
            }
        }
        
        [Required()]
        [DataType(DataType.DateTime)]
        [Display(Name = "Start date")]
        public System.DateTime StartDate {
            get {
                return this._startDate;
            }
            set {
                this._startDate = value;
            }
        }
        
        [Required()]
        [DataType(DataType.DateTime)]
        [Display(Name = "End date")]
        public System.DateTime EndDate {
            get {
                return this._endDate;
            }
            set {
                this._endDate = value;
            }
        }
        
        [Required()]
        [Display(Name = "Min qty")]
        public int MinQty {
            get {
                return this._minQty;
            }
            set {
                this._minQty = value;
            }
        }
        
        [Display(Name = "Max qty")]
        public int? MaxQty {
            get {
                return this._maxQty;
            }
            set {
                this._maxQty = value;
            }
        }
        
        [Display(Name = "Rowguid")]
        public System.Guid Rowguid {
            get {
                return this._rowguid;
            }
        }
        
        [Required()]
        [DataType(DataType.DateTime)]
        [Display(Name = "Modified date")]
        public System.DateTime ModifiedDate {
            get {
                return this._modifiedDate;
            }
            set {
                this._modifiedDate = value;
            }
        }
        
        /// Child SpecialOfferProducts where [SpecialOfferProduct].[SpecialOfferID] point to this entity (FK_SpecialOfferProduct_SpecialOffer_SpecialOfferID)
        public virtual ICollection<SpecialOfferProductModel> SpecialOfferProductsModel { get; set; } = new HashSet<SpecialOfferProductModel>();
        
        public override int GetHashCode() {
            int hash = 0;
            hash ^=Rowguid.GetHashCode();
            return hash;
        }
        
        public override string ToString() {
            return Description
                 + "-" + DiscountPct.ToString()
                 + "-" + Type
                 + "-" + Category
                 + "-" + StartDate.ToShortDateString()
                 + "-" + EndDate.ToShortDateString()
                 + "-" + MinQty.ToString()
;
        }
        
        public override bool Equals(object obj) {
        bool result = false;

            if (obj is SpecialOfferModel) {
                SpecialOfferModel toCompare = (SpecialOfferModel)obj;
              if(toCompare != null)
              {
                  result = Equals(toCompare);
              }
            }

            return result;
        }
        
        public virtual bool Equals(SpecialOfferModel toCompare) {

        bool result = false;

            if (toCompare != null) {
                result = string.Compare(toCompare.Description, Description, true) == 0
             && toCompare.DiscountPct == DiscountPct
             && string.Compare(toCompare.Type, Type, true) == 0
             && string.Compare(toCompare.Category, Category, true) == 0
             && toCompare.StartDate.Equals(StartDate)
             && toCompare.EndDate.Equals(EndDate)
             && toCompare.MinQty == MinQty
             && toCompare.MaxQty.Equals(MaxQty)
;
            }

            return result;
        }
    }
}

