// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using SalesAPI.Entities;
using SalesAPI.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SalesAPI.Models {
    
    
    public class SpecialOfferProductModel {
        
        protected internal int _specialOfferID;
        
        protected internal int _productID;
        
        protected internal System.Guid _rowguid;
        
        protected internal System.DateTime _modifiedDate;
        
        public SpecialOfferProductModel() {
        }
        
        internal SpecialOfferProductModel(SpecialOfferProduct entity) {
            this._specialOfferID = entity.SpecialOfferID;
            this._productID = entity.ProductID;
            _rowguid = entity.Rowguid;
            this._modifiedDate = entity.ModifiedDate;
        }
        
        [Required()]
        [Display(Name = "Special offer ID")]
        public int SpecialOfferID {
            get {
                return this._specialOfferID;
            }
            set {
                this._specialOfferID = value;
            }
        }
        
        [Required()]
        [Display(Name = "Product ID")]
        public int ProductID {
            get {
                return this._productID;
            }
            set {
                this._productID = value;
            }
        }
        
        [Display(Name = "Rowguid")]
        public System.Guid Rowguid {
            get {
                return this._rowguid;
            }
        }
        
        [Required()]
        [DataType(DataType.DateTime)]
        [Display(Name = "Modified date")]
        public System.DateTime ModifiedDate {
            get {
                return this._modifiedDate;
            }
            set {
                this._modifiedDate = value;
            }
        }
        
        /// Child SalesOrderDetails where [SalesOrderDetail].([ProductID], [SpecialOfferID]) point to this entity (FK_SalesOrderDetail_SpecialOfferProduct_SpecialOfferIDProductID)
        public virtual ICollection<SalesOrderDetailModel> SalesOrderDetailsModel { get; set; } = new HashSet<SalesOrderDetailModel>();
        
        public override int GetHashCode() {
            int hash = 0;
            hash ^=SpecialOfferID.GetHashCode();
            hash ^=ProductID.GetHashCode();
            return hash;
        }
        
        public override string ToString() {
            return SpecialOfferID.ToString()
                 + "-" + ProductID.ToString()
;
        }
        
        public override bool Equals(object obj) {
        bool result = false;

            if (obj is SpecialOfferProductModel) {
                SpecialOfferProductModel toCompare = (SpecialOfferProductModel)obj;
              if(toCompare != null)
              {
                  result = Equals(toCompare);
              }
            }

            return result;
        }
        
        public virtual bool Equals(SpecialOfferProductModel toCompare) {

        bool result = false;

            if (toCompare != null) {
                result = toCompare.SpecialOfferID == SpecialOfferID
             && toCompare.ProductID == ProductID
;
            }

            return result;
        }
    }
}

